DECLARE
    CURSOR C_CUSTOMERS IS
    SELECT
        C.CUSTOMERID,
        L.LOANID,
        L.INTERESTRATE
    FROM
        CUSTOMERS C
        JOIN LOANS L
        ON C.CUSTOMERID = L.CUSTOMERID
    WHERE
        TRUNC(MONTHS_BETWEEN(SYSDATE, C.DOB) / 12) > 60;
BEGIN
    FOR REC IN C_CUSTOMERS LOOP
        UPDATE LOANS
        SET
            INTERESTRATE = REC.INTERESTRATE - 1
        WHERE
            LOANID = REC.LOANID;
    END LOOP;

    COMMIT;
END;