SET SERVEROUTPUT ON;

DECLARE
    CURSOR C_TRANSACTIONS IS
    SELECT
        DISTINCT C.CUSTOMERID,
        C.NAME,
        T.TRANSACTIONDATE,
        T.AMOUNT,
        T.TRANSACTIONTYPE
    FROM
        CUSTOMERS    C
        JOIN ACCOUNTS A
        ON C.CUSTOMERID = A.CUSTOMERID
        JOIN TRANSACTIONS T
        ON A.ACCOUNTID = T.ACCOUNTID
    WHERE
        EXTRACT(MONTH FROM T.TRANSACTIONDATE) = EXTRACT(MONTH FROM SYSDATE)
        AND EXTRACT(YEAR FROM T.TRANSACTIONDATE) = EXTRACT(YEAR FROM SYSDATE);
    V_CUSTOMERID      CUSTOMERS.CUSTOMERID%TYPE;
    V_NAME            CUSTOMERS.NAME%TYPE;
    V_TRANSACTIONDATE TRANSACTIONS.TRANSACTIONDATE%TYPE;
    V_AMOUNT          TRANSACTIONS.AMOUNT%TYPE;
    V_TRANSACTIONTYPE TRANSACTIONS.TRANSACTIONTYPE%TYPE;
BEGIN
    OPEN C_TRANSACTIONS;
    LOOP
        FETCH C_TRANSACTIONS INTO V_CUSTOMERID, V_NAME, V_TRANSACTIONDATE, V_AMOUNT, V_TRANSACTIONTYPE;
        EXIT WHEN C_TRANSACTIONS%NOTFOUND;
 
        -- Print the statement (for demonstration purposes, using DBMS_OUTPUT)
        DBMS_OUTPUT.PUT_LINE('CustomerID: '
                             || V_CUSTOMERID);
        DBMS_OUTPUT.PUT_LINE('Name: '
                             || V_NAME);
        DBMS_OUTPUT.PUT_LINE('Transaction Date: '
                             || V_TRANSACTIONDATE);
        DBMS_OUTPUT.PUT_LINE('Amount: '
                             || V_AMOUNT);
        DBMS_OUTPUT.PUT_LINE('Transaction Type: '
                             || V_TRANSACTIONTYPE);
        DBMS_OUTPUT.PUT_LINE('--------------------------');
    END LOOP;

    CLOSE C_TRANSACTIONS;
END;
/