CREATE OR REPLACE PACKAGE EMPLOYEEMANAGEMENT AS

    PROCEDURE HIRENEWEMPLOYEE(
        P_EMPLOYEE_ID IN NUMBER,
        P_NAME IN VARCHAR2,
        P_POSITION IN VARCHAR2,
        P_SALARY IN NUMBER,
        P_DEPARTMENT IN VARCHAR2,
        P_HIRE_DATE IN DATE
    );

    PROCEDURE UPDATEEMPLOYEEDETAILS(
        P_EMPLOYEE_ID IN NUMBER,
        P_NAME IN VARCHAR2,
        P_SALARY IN NUMBER,
        P_DEPARTMENT IN VARCHAR2
    );

    FUNCTION CALCULATEANNUALSALARY(
        P_SALARY IN NUMBER
    ) RETURN NUMBER;
END EMPLOYEEMANAGEMENT;
/

CREATE OR REPLACE PACKAGE BODY EMPLOYEEMANAGEMENT AS

    PROCEDURE HIRENEWEMPLOYEE(
        P_EMPLOYEE_ID IN NUMBER,
        P_NAME IN VARCHAR2,
        P_POSITION IN VARCHAR2,
        P_SALARY IN NUMBER,
        P_DEPARTMENT IN VARCHAR2,
        P_HIRE_DATE IN DATE
    ) IS
    BEGIN
        INSERT INTO EMPLOYEES (
            EMPLOYEEID,
            NAME,
            POSITION,
            SALARY,
            DEPARTMENT,
            HIREDATE
        ) VALUES (
            P_EMPLOYEE_ID,
            P_NAME,
            P_POSITION,
            P_SALARY,
            P_DEPARTMENT,
            P_HIRE_DATE
        );
        COMMIT;
    END HIRENEWEMPLOYEE;

    PROCEDURE UPDATEEMPLOYEEDETAILS(
        P_EMPLOYEE_ID IN NUMBER,
        P_NAME IN VARCHAR2,
        P_SALARY IN NUMBER,
        P_DEPARTMENT IN VARCHAR2
    ) IS
    BEGIN
        UPDATE EMPLOYEES
        SET
            NAME = P_NAME,
            SALARY = P_SALARY,
            DEPARTMENT = P_DEPARTMENT
        WHERE
            EMPLOYEEID = P_EMPLOYEE_ID;
        COMMIT;
    END UPDATEEMPLOYEEDETAILS;

    FUNCTION CALCULATEANNUALSALARY(
        P_SALARY IN NUMBER
    ) RETURN NUMBER IS
    BEGIN
        RETURN P_SALARY * 12;
    END CALCULATEANNUALSALARY;
END EMPLOYEEMANAGEMENT;
/